### ISSUE TITLE
Some questions about the reported results

### ISSUE THREAD

**Issue by QiushiYang** [islam-nassar/semco#3]
Thanks a lot for your released codes and your excellent work. I have some questions about the reported results in your paper.
(1) Does the reported results are obtained by calculating the mean accuracy value of the latest several (e.g., 20) iterations/epochs during the training phase or just select the best accuracy of someone iteration/epoch, or any other protocols?
(2) Does all reported results (and the re-implemented FixMatch & MixMatch) are obtained by final EMA models (which seems better than student models, and the reported results in original FixMatch paper)?
(3) As your paper indicates, the total training epoch is only 300, did you try to train model with more epochs on CIFAR (e.g., 1024 epochs as many other SOTA works did for fair comparison)?

**Comment by islam-nassar** [comment]
Hi,
1) The reported results is the mean accuracy of the last epoch, averaged over 3/5 different runs.
2) Yes, the reported results are all the EMA model's
3) No. we only trained for 300 epochs as our system generally converged much faster than baselines. However, we trained all the comparison systems also for 300 epochs for a fair comparison.
