### ISSUE TITLE
OSError: [Errno 22] Invalid argument: 

### ISSUE THREAD

**Issue by aihcyllop** [islam-nassar/semco#4]
When I run cifar100  with semco model, I face the problem: 

OSError: [Errno 22] Invalid argument: '\\Desktop\\semco-main\\data\\cifar100\\x2500\\2022-02-16_17:10:56_2500_labelled_instances.log'

How can I do for this problem, thanks!

**Comment by islam-nassar** [comment]
Can you send the script you use to launch the job to reproduce your issue?

**Comment by aihcyllop** [comment]
python launch_semco.py --word-vec-path C:/Users/Aihcyllop/Desktop/semco-main/numberbatch-en-19.08_128D.dict.pkl --dataset-name cifar100 --train-split-pickle splits/cifar100_labelled_data_25_seed123.pkl --model_backbone=wres --wres-k=2 --no_amp

Thanks!

**Comment by islam-nassar** [comment]
I used the launch script you sent and it is working fine on my end. Can you provide the full traceback so I can help you troubleshoot. Also can you describe your environment details.

**Comment by aihcyllop** [comment]
The message shows below:

C:\Users\Aihcyllop\anaconda3\envs\semco\python.exe C:/Users/Aihcyllop/Desktop/semco-main/launch_semco.py --word-vec-path C:/Users/Aihcyllop/Desktop/semco-main/numberbatch-en-19.08_128D.dict.pkl --dataset-name cifar100 --train-split-pickle splits/cifar100_labelled_data_25_seed123.pkl --model_backbone=wres --wres-k=2 --no_amp

Using cifar100 stats for normalization
Attempting to load Word Vectors from file..
last word in aquarium_fish is a noun, setting label to it: fish
Grouping labels using DBscan....
100 labels were grouped into 95 groups.
['aquarium_fish', 'trout'] are grouped together.
['boy', 'girl'] are grouped together.
['crab', 'lobster'] are grouped together.
['man', 'woman'] are grouped together.
['oak_tree', 'pine_tree'] are grouped together.

C:\Users\Aihcyllop\Desktop\semco-main\model\label_embedding_guessor.py:29: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ..\torch\csrc\utils\tensor_new.cpp:201.)
  self.embedding_matrix = torch.tensor([class_2_embeddings_dict[cls] for cls in classes]).to(device)
Traceback (most recent call last):
  File "C:/Users/Aihcyllop/Desktop/semco-main/launch_semco.py", line 46, in <module>
    model = SemCo(args, dataset_meta, device, L)
  File "C:\Users\Aihcyllop\Desktop\semco-main\model\semco.py", line 59, in __init__
    self.logger, self.writer, self.time_stamp = self._setup_default_logging()
  File "C:\Users\Aihcyllop\Desktop\semco-main\model\semco.py", line 528, in _setup_default_logging
    level=default_level)
  File "C:\Users\Aihcyllop\anaconda3\envs\semco\lib\logging\__init__.py", line 1898, in basicConfig
    h = FileHandler(filename, mode)
  File "C:\Users\Aihcyllop\anaconda3\envs\semco\lib\logging\__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\Aihcyllop\anaconda3\envs\semco\lib\logging\__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 22] Invalid argument: 'C:\\\Users\\\Aihcyllop\\\Desktop\\\semco-main\\\data\\\cifar100\\\x2500\\\2022-02-17_13:06:41_2500_labelled_instances.log'

Process finished with exit code 1

**Comment by aihcyllop** [comment]
My environment and I use Windows10 system and python=3.7, thanks!   
absl-py                0.11.0
albumentations         1.1.0
apex                   0.1
argcomplete            1.12.3
argon2-cffi            21.3.0
argon2-cffi-bindings   21.2.0
attrs                  21.4.0
backcall               0.2.0
bleach                 4.1.0
boto                   2.49.0
cached-property        1.5.2
cachetools             4.2.1
certifi                2021.10.8
cffi                   1.14.6
chardet                3.0.4
charset-normalizer     2.0.10
click                  8.0.1
cloudpickle            1.6.0
colorama               0.4.4
crcmod                 1.7
cryptography           3.4.7
cycler                 0.10.0
Cython                 0.29.21
debugpy                1.5.1
decorator              5.1.1
defusedxml             0.7.1
diffdist               0.1
entrypoints            0.4
fasteners              0.16.3
filelock               3.0.12
gcs-oauth2-boto-plugin 2.7
gensim                 4.0.1
google-apitools        0.5.32
google-auth            1.24.0
google-auth-oauthlib   0.4.2
google-reauth          0.1.1
grpcio                 1.35.0
gsutil                 4.65
gym                    0.18.3
h5py                   3.2.1
higher                 0.2.1
httplib2               0.19.1
huggingface-hub        0.0.12
idna                   2.8
imageio                2.14.0
importlib-metadata     3.4.0
importlib-resources    5.4.0
ipdb                   0.13.3
ipykernel              6.9.0
ipython                7.31.1
ipython-genutils       0.2.0
ipywidgets             7.6.5
jedi                   0.18.1
Jinja2                 3.0.3
joblib                 1.0.1
jsonschema             4.4.0
jupyter                1.0.0
jupyter-client         7.1.2
jupyter-console        6.4.0
jupyter-core           4.9.1
jupyterlab-pygments    0.1.2
jupyterlab-widgets     1.0.2
kiwisolver             1.3.1
learn2learn            0.1.5
Markdown               3.3.3
MarkupSafe             2.0.1
matplotlib             3.1.3
matplotlib-inline      0.1.3
MetaNN                 0.2.9
mistune                0.8.4
mkl-fft                1.3.1
mkl-random             1.2.2
mkl-service            2.4.0
mock                   2.0.0
monotonic              1.6
nbclient               0.5.10
nbconvert              6.4.1
nbformat               5.1.3
nest-asyncio           1.5.4
networkx               2.6.3
nltk                   3.4.5
notebook               6.4.8
numpy                  1.18.1
oauth2client           4.1.3
oauthlib               3.1.0
olefile                0.46
opencv-python          4.5.5.62
opencv-python-headless 4.5.5.62
packaging              21.0
pandas                 1.0.1
pandocfilters          1.5.0
parso                  0.8.3
pbr                    5.6.0
pickleshare            0.7.5
Pillow                 7.2.0
pip                    21.2.4
progress               1.5
prometheus-client      0.13.1
prompt-toolkit         3.0.27
protobuf               3.14.0
pyarrow                7.0.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pycparser              2.20
pyglet                 1.5.15
Pygments               2.11.2
pyOpenSSL              20.0.1
pyparsing              2.4.7
pyrsistent             0.18.1
python-dateutil        2.8.1
pytz                   2021.3
pyu2f                  0.1.5
PyWavelets             1.2.0
pywin32                303
pywinpty               2.0.2
PyYAML                 5.4.1
pyzmq                  22.3.0
qtconsole              5.2.2
QtPy                   2.0.1
qudida                 0.0.4
regex                  2021.8.3
requests               2.22.0
requests-oauthlib      1.3.0
retry-decorator        1.1.1
rsa                    4.7
sacremoses             0.0.45
scikit-image           0.19.1
scikit-learn           0.23.2
scipy                  1.6.1
Send2Trash             1.8.0
setuptools             58.0.4
six                    1.16.0
sklearn                0.0
smart-open             5.1.0
tensorboard            2.4.1
tensorboard-plugin-wit 1.8.0
tensorboardX           2.1
terminado              0.13.1
testpath               0.5.0
threadpoolctl          2.1.0
tifffile               2021.11.2
tokenizers             0.10.3
torch                  1.10.1
torchaudio             0.10.1
torchsummary           1.5.1
torchvision            0.11.2
tornado                6.1
tqdm                   4.42.1
traitlets              5.1.1
transformers           4.9.2
typing-extensions      3.10.0.2
urllib3                1.25.11
wcwidth                0.2.5
webencodings           0.5.1
Werkzeug               1.0.1
wheel                  0.37.1
widgetsnbextension     3.5.2
wincertstore           0.2
zipp                   3.4.0

**Comment by islam-nassar** [comment]
According to [this](https://python-forum.io/Thread-SOLVED-OSError-Errno-22-Invalid-argument?page=2) post, the colon is not allowed in the filename in Windows. You can fix this error by changing the timing format in [L527](https://github.com/islam-nassar/semco/blob/5b46c2bfabbb3fc17badcd1f01ac74f347f6bcc9/model/semco.py#L527) from "%m/%d/%Y %H:%M:%S" to "%m-%d-%H-%M-%S.%f". I'll make an update in later versions. Thanks!

**Comment by aihcyllop** [comment]
I changed my L527 to "%m-%d-%H-%M-%S.%f".
It still have the error:
OSError: [Errno 22] Invalid argument: 'C:\\\Users\\\Aihcyllop\\\Desktop\\\semco-main\\\data\\\cifar100\\\x2500\\\2022-02-17_16:58:43_2500_labelled_instances.log'

My error is show that  L528: level=default_level)
Does this line I should change? Thanks

**Comment by islam-nassar** [comment]
you should change the datefmt argument. 
I just noticed that you also need to change [this](https://github.com/islam-nassar/semco/blob/5b46c2bfabbb3fc17badcd1f01ac74f347f6bcc9/model/semco.py#L523) line to:

`time_stamp = time_str(fmt="%m-%d-%H-%M-%S.%f")` 

The idea is to make sure that the log file name has no colon in it.

**Comment by aihcyllop** [comment]
The problem had been solved!
Thanks a lot!!!
