### ISSUE TITLE
The result of Epoch 299. Top1

### ISSUE THREAD

**Issue by aihcyllop** [islam-nassar/semco#5]
When I run the following command, I got the result:
- INFO - train -   Epoch 299. Top1: 65.9493. Top5: 88.9249 result.
I want to ask what other parameters can be adjusted to achieve better result, thank you!
Or did I write something wrong? Thank you!

=======
command
=======
--word-vec-path C:/Users/Aihcyllop/Desktop/semco-main/numberbatch-en-19.08_128D.dict.pkl --dataset-name cifar100 --train-split-pickle splits/cifar100_labelled_data_25_seed123.pkl --model_backbone=wres --wres-k=2 --no_amp 

=======
result
=======
2022-02-19 07:11:57,178 - INFO - train -   Epoch 299. Top1: 65.9493. Top5: 88.9249. Top1_emb: 65.2811. Top5_emb: 82.3998. Top1_comb: 65.5660. best_metric: 66.1557 in epoch282
2022-02-19 07:11:57,180 - INFO - train -   Break epoch is reached

**Comment by islam-nassar** [comment]
Hi,

If you look at the results in our paper, this is the best result you can get with the current configuration (2500 labelled samples, mu=3). If you want to get the 68.01%, you need to use mu=7
